version: '3.7'

services:
  # =app
  app:
    image: "sindriainc/ansible:latest"
    container_name: "${APP_NAME}"
    volumes:
      - "${CODE_PATH}:${APP_CODE_PATH}/${APP_NAME}"
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: "${APP_NAME}.local"    
    working_dir: "${APP_CODE_PATH}/${APP_NAME}"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #   vpc_<app-name>:
    #     ipv4_address: "${APP_IP_ADDRESS}"
    #     aliases:
    #       - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_${APP_NAME}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:        
#  vpc_<app-name>:
#    external: true 
